[
    {
        "test_name": "test_flaky",
        "test_file": "test_auth.py",
        "test_class": "TestFlaky",
        "duration": 2.3,
        "status": "FAIL",
        "error_message": "Timeout Error",
        "environment": "staging",
        "framework": "pytest",
        "timestamp": "2025-03-16T14:41:24.291123"
    },
    {
        "test_name": "test_login",
        "test_file": "test_auth.py",
        "test_class": "TestLogin",
        "duration": 1.2,
        "status": "PASS",
        "error_message": null,
        "environment": "staging",
        "framework": "pytest",
        "timestamp": "2025-03-16T14:43:00.158214"
    },
    {
        "test_name": "test_login",
        "test_file": "test_auth.py",
        "test_class": "TestLogin",
        "duration": 1.5,
        "status": "FAIL",
        "error_message": "Timeout Error",
        "environment": "staging",
        "framework": "pytest",
        "timestamp": "2025-03-16T14:47:09.448691"
    },
    {
        "test_name": "test_login",
        "test_file": "test_auth.py",
        "test_class": "TestLogin",
        "duration": 1.2,
        "status": "PASS",
        "error_message": null,
        "environment": "staging",
        "framework": "pytest",
        "timestamp": "2025-03-16T14:48:35.434049"
    },
    {
        "test_name": "test_login",
        "test_file": "test_auth.py",
        "test_class": "TestLogin",
        "duration": 1.2,
        "status": "PASS",
        "error_message": null,
        "environment": "staging",
        "framework": "pytest",
        "timestamp": "2025-03-16T14:48:36.595719"
    },
    {
        "test_name": "test_login",
        "test_file": "test_auth.py",
        "test_class": "TestLogin",
        "duration": 1.2,
        "status": "PASS",
        "error_message": null,
        "environment": "staging",
        "framework": "pytest",
        "timestamp": "2025-03-16T14:48:37.337653"
    }
]